<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAcceptAll</name>
   <tag></tag>
   <elementGuidId>5859e066-37bf-4a45-bab0-463aa00d62db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cookiescript_accept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cookiescript_accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd007ea6-c220-42b5-b2b4-54c2cdb1acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiescript_accept</value>
      <webElementGuid>049434c1-c7d1-4dba-9985-47ea83f56ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>605dab7f-99a5-4ef3-90f1-58bf173e10cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b5e0b19-dfab-4bcc-9ccf-0c53256bee92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cs-i18n-text</name>
      <type>Main</type>
      <value>{&quot;en&quot;:&quot;Accept all&quot;}</value>
      <webElementGuid>4d9c8267-b2fe-4624-9fef-568280894d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Accept all      </value>
      <webElementGuid>992afa18-89ec-46fe-9325-135a85fa3e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiescript_accept&quot;)</value>
      <webElementGuid>50e18a7d-2118-4b4c-9968-8f72a27c2835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cookiescript_accept']</value>
      <webElementGuid>6de546e9-95e0-4120-95ab-b73343a57cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiescript_buttons']/div</value>
      <webElementGuid>24276cb0-0c74-432b-97ee-49fcb235cd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide details'])[1]/following::div[3]</value>
      <webElementGuid>4b886bd5-c920-4427-87b3-38dffdac5d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show details'])[1]/following::div[3]</value>
      <webElementGuid>95944970-58a8-40fd-a249-f19e1fac08a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline all'])[1]/preceding::div[1]</value>
      <webElementGuid>6fefb91f-157a-4e56-b286-57076b70347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept all']/parent::*</value>
      <webElementGuid>a0c5f5a8-fe09-4f8e-a3e1-c948869ca18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div</value>
      <webElementGuid>30358d9a-77d4-4989-ad9c-3d14b1a8a3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cookiescript_accept' and (text() = '
        Accept all      ' or . = '
        Accept all      ')]</value>
      <webElementGuid>2c2cf109-1235-4188-82f5-59fe25ec3f2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
