<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTimeAttendance</name>
   <tag></tag>
   <elementGuidId>8fe099d0-c630-41e5-8351-ce7943ea3b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-disclosure-button-1003']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-disclosure-button-1003</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4df66b26-ac08-4714-b715-b4d5b2bfe9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex w-full flex-wrap items-center py-6 pr-8 text-left text-lg font-medium text-black</value>
      <webElementGuid>6118a5f6-5f92-44e7-9ed5-45c363b49857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-disclosure-button-1003</value>
      <webElementGuid>0305dc30-50ae-4a5c-b956-687851218be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3073f79-298a-415c-8b76-342ce9de8523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>612e639c-ebec-4de3-8fd4-6f504708802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-disclosure-panel-8</value>
      <webElementGuid>d489f93f-acd2-4ed3-b079-c30d4b2b4d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time &amp; Attendance</value>
      <webElementGuid>5a84a981-09ff-403a-9ae7-19d5a14c0577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-button-1003&quot;)</value>
      <webElementGuid>3e0ffd65-91af-4414-bc92-d2fb98dcb198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-disclosure-button-1003']</value>
      <webElementGuid>cc96fd0c-4183-4449-9163-0b9bc2dff127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div[4]/div[3]/section[3]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>0a4a5150-61d7-48e0-8f4d-b37616b95182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>2f965a72-2597-4285-afe2-1c1998db1d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rostering &amp; Scheduling'])[2]/following::button[1]</value>
      <webElementGuid>c1b90f96-a660-4e58-9646-e66d555c911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[2]/preceding::button[1]</value>
      <webElementGuid>e5699149-a747-4d31-9a79-70dc1466b9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>4509b2e4-2e12-44fa-b031-6caef8f1e3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-disclosure-button-1003' and @type = 'button' and (text() = 'Time &amp; Attendance' or . = 'Time &amp; Attendance')]</value>
      <webElementGuid>4e7605fc-08a0-4d70-a478-01820aaf336f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
