<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Done_EM</name>
   <tag></tag>
   <elementGuidId>2f3ee16d-9800-4229-8135-30b2cb226931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-2']/div[2]/div[2]/div[18]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.plainButton.return</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2711da4a-539b-4759-81fd-8ab2459ce469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plainButton return</value>
      <webElementGuid>8c70d1cd-c651-4fbb-b3cd-4d078dc2fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>330a5e4a-4d63-4f83-8f8c-23c57a6ce327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-2&quot;)/div[@class=&quot;flex-container employee-edit-container&quot;]/div[@class=&quot;col-right&quot;]/div[@class=&quot;employee-edit-item&quot;]/div[@class=&quot;value flex-end&quot;]/span[@class=&quot;plainButton return&quot;]</value>
      <webElementGuid>50e69215-65f2-4b83-8a9d-576bc3cd25e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-2']/div[2]/div[2]/div[18]/div/span</value>
      <webElementGuid>5ce2c8bf-b821-489f-aa41-6ca8b2bb5bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank State'])[1]/following::span[1]</value>
      <webElementGuid>57651cb3-896e-492e-9804-0f39eedbd4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment'])[1]/preceding::span[1]</value>
      <webElementGuid>70a10c50-4344-4f3b-91dd-dbedf093a684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>4f78a984-3d0e-4f2f-af6c-89832a88cca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/span</value>
      <webElementGuid>5f53b839-c74c-4c7f-bf3f-2947995fb933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>66cac121-faeb-4c47-8088-2b9d3c5635cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
