<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Save</name>
   <tag></tag>
   <elementGuidId>bdab27d9-fa4f-4d33-aa38-3481b5277bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='TimesheetEditor_Button_SaveChanges']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TimesheetEditor_Button_SaveChanges</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a545bb63-c005-472c-8ed2-bb5aa0d7d35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hf-button hf-button--size-middle hf-button--bg-yellow</value>
      <webElementGuid>b52f9a82-a01f-46d0-bd2e-a32995fbab9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TimesheetEditor_Button_SaveChanges</value>
      <webElementGuid>152f1d05-d6ed-496e-84f6-e9e2a32993e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>51ab0a02-01a3-4bd8-bcb8-e4acefbc1c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TimesheetEditor_Button_SaveChanges&quot;)</value>
      <webElementGuid>8428f076-5b31-46d5-9569-6ecbe0c5d637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='TimesheetEditor_Button_SaveChanges']</value>
      <webElementGuid>b8e4af1e-3ecb-4293-8c75-a8eced721b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kendo-dialog-content-627349']/hf-timesheet-editor/hf-dialog-layout/div/div[2]/div[5]/hf-button[2]/div/button</value>
      <webElementGuid>91c84db1-74a0-4ad4-84da-18bde427b006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>72f968de-6f62-4ff9-84d5-3dcf2af17bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Award Breakdown'])[1]/following::button[2]</value>
      <webElementGuid>0da612de-c131-4e3b-ad07-6aca48816946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheets'])[2]/preceding::button[1]</value>
      <webElementGuid>3689f642-4f96-4d53-a42e-dda0641217a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hf-button[2]/div/button</value>
      <webElementGuid>7f7b8823-aead-40da-a7e0-200a58c5ceb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'TimesheetEditor_Button_SaveChanges' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>6c5beb57-3c82-4e8a-82dd-3db35c924a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
