<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_New</name>
   <tag></tag>
   <elementGuidId>2ec5b952-f44d-42f3-a30c-e600466c79e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//hf-shared-button-new[@id='TimesheetHeader_Button_CreateTimesheet']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.hf-button-new.hf-button-new--left-icon.hf-button-new--size-large.hf-button-new--type-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3358ad5-8378-4795-8fc6-aef9eef70b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hf-button-new hf-button-new--left-icon hf-button-new--size-large hf-button-new--type-primary</value>
      <webElementGuid>782e8abc-abe7-4036-adf4-87ecabe415c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>ab857f7f-6848-43a1-a31e-d139c8aa200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TimesheetHeader_Button_CreateTimesheet&quot;)/button[@class=&quot;hf-button-new hf-button-new--left-icon hf-button-new--size-large hf-button-new--type-primary&quot;]</value>
      <webElementGuid>94539888-3a19-4c8a-b625-5f3e0e234280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//hf-shared-button-new[@id='TimesheetHeader_Button_CreateTimesheet']/button</value>
      <webElementGuid>41999889-3d3d-4a54-8d4e-2bef72d87aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheets'])[2]/following::button[1]</value>
      <webElementGuid>cceefc38-56b2-47d3-b395-b00b9b2710a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All timesheets (0)'])[1]/preceding::button[2]</value>
      <webElementGuid>e43ef562-5c5a-4e7a-9481-387c2218b614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hf-shared-button-new/button</value>
      <webElementGuid>a82e988a-5349-43e3-9510-8c1397979884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'New' or . = 'New')]</value>
      <webElementGuid>ce321686-466a-46c6-9f95-d621799c0f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
