<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Done</name>
   <tag></tag>
   <elementGuidId>a7325d32-9b2a-4795-824e-19a195bfd8ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='EmployeeSelector_Button_SelectEmployee']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmployeeSelector_Button_SelectEmployee</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ed9481a-8d83-4a2f-99cd-378e25a2e9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hf-button-new hf-button-new--size-large hf-button-new--type-primary</value>
      <webElementGuid>bf2cf81c-f04f-4b84-b255-751e9237bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmployeeSelector_Button_SelectEmployee</value>
      <webElementGuid>2daa9cbf-a19d-4185-b372-df9fab839dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>ae80a698-8d29-4d62-916f-7173c73d3b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmployeeSelector_Button_SelectEmployee&quot;)</value>
      <webElementGuid>f4f70486-d357-4c62-a741-1a8593d38baa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='EmployeeSelector_Button_SelectEmployee']</value>
      <webElementGuid>40408eb4-8f98-4d00-a80a-c0e9704a8ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kendo-dialog-content-397103']/hf-employee-selector/hf-dialog-layout/div/div[2]/div/div/hf-shared-button-new/button</value>
      <webElementGuid>d498ba30-5a9e-4780-9473-c65543fe239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>b5daf19d-2302-4006-bdd9-b6d9f49f3814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/following::button[2]</value>
      <webElementGuid>6c69a9be-02b1-467d-a7f5-a3ac49bbb261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheets'])[2]/preceding::button[1]</value>
      <webElementGuid>d5e1c036-146a-4299-899d-b7d181815b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/hf-shared-button-new/button</value>
      <webElementGuid>74e48533-938e-4297-a26f-02794b770522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'EmployeeSelector_Button_SelectEmployee' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>5b02680d-5b24-4411-9857-0cab7ba3c074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
