<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Default</name>
   <tag></tag>
   <elementGuidId>03087001-7eba-41dd-9fc9-46343e41b747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-container']/div/div/hf-action-dropdown-button/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.action-dropdown-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25f37c5f-72d3-478f-9510-3e6f39fdf9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-dropdown-button</value>
      <webElementGuid>e91e84ee-5559-4635-848b-69fbf908f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Timesheets from defaults </value>
      <webElementGuid>df0abed3-829c-4d70-ac54-54c8424bfc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-container&quot;)/div[@class=&quot;page-wide&quot;]/div[@class=&quot;hf-action-dropdown__content hf-action-dropdown__content--right-aligned ng-star-inserted&quot;]/hf-action-dropdown-button[1]/button[@class=&quot;action-dropdown-button&quot;]</value>
      <webElementGuid>0e2fb636-a211-4e97-aa4b-d0f5a1ef4628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-container']/div/div/hf-action-dropdown-button/button</value>
      <webElementGuid>c7a3fdea-ff30-4e1d-a3c8-cc82e88122f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::button[1]</value>
      <webElementGuid>2351fb83-9060-4fed-9913-9f8f9469aedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost'])[2]/following::button[1]</value>
      <webElementGuid>0e1804d1-7fd0-46c3-b309-821f91225784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheets from roster'])[1]/preceding::button[1]</value>
      <webElementGuid>cb16323c-e524-4d7c-9206-f28b887a8391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/preceding::button[2]</value>
      <webElementGuid>5488b664-65f8-46f1-b139-be2f60b8cebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Timesheets from defaults']/parent::*</value>
      <webElementGuid>01eac1d3-0a93-4588-84be-5c273b94ace7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hf-action-dropdown-button/button</value>
      <webElementGuid>c23d8bad-2fcb-409d-a9dc-4b37b6469fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Timesheets from defaults ' or . = ' Timesheets from defaults ')]</value>
      <webElementGuid>24dd2738-d28f-4889-a11d-0096813ae0ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
