<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Delete</name>
   <tag></tag>
   <elementGuidId>b2df6b82-e14e-4e54-8103-1d0e2068ffd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>201916e6-ff9c-4db8-8c71-ad1ad24c416d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hf-button hf-button--primary hf-button--inherit-parent-cursor</value>
      <webElementGuid>2b3bdb05-6ec9-4e6b-bc3c-a747a9e9bd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01</value>
      <webElementGuid>e470f4de-8a0f-49d0-9b66-ca66dcd13c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>a2c12f85-5ba7-4f38-9870-4c6e85a520c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01&quot;)</value>
      <webElementGuid>de9b5983-7ea5-4aa3-b5ef-3f6c43c007b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01']</value>
      <webElementGuid>d22b2799-26ce-4629-aab3-9dbc1de20196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-container']/div/div/hf-action-dropdown-button/button/div/div/hf-button/div/button</value>
      <webElementGuid>6b205a65-113b-43b8-9a1e-9458200720e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::button[2]</value>
      <webElementGuid>a3418af9-cd1c-4d2f-b3c0-18cdfaf3b61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost'])[2]/following::button[2]</value>
      <webElementGuid>d722406c-f3f1-456f-9852-fa3677c021b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/preceding::button[1]</value>
      <webElementGuid>e2142fb1-c466-4ade-9dff-a45c3c924fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>e159f843-b650-4d19-87c6-d2a10107b01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'TimesheetGrid_Button_DeleteUndeleteTimesheet_MGR01' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>71cda31e-c1e9-4c8f-898a-a6b75d2d9d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
