<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Home_SidePanel</name>
   <tag></tag>
   <elementGuidId>cbba7bf9-4997-4fd1-99d5-d06104d2c71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MenuItem_Button_Home']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuItem_Button_Home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dcf46420-8762-4cac-83ef-6d9bfc395e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item menu-item--icon menu-item--icon-home menu-item--link</value>
      <webElementGuid>8172df83-8805-4c0e-b596-8c632fd78654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuItem_Button_Home</value>
      <webElementGuid>aa532e67-6518-40ab-a109-5eccc1ca7288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Home</value>
      <webElementGuid>d848c89a-f81e-4677-a1bb-e48b5e815916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>8f9f6d17-a234-474b-b635-681717bb78a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuItem_Button_Home&quot;)</value>
      <webElementGuid>aa525dbb-3761-46e9-88f3-0e5bac51db96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MenuItem_Button_Home']</value>
      <webElementGuid>9499513d-8166-4bd8-86c6-11216bcaa125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='intelliHR'])[1]/following::a[1]</value>
      <webElementGuid>c1796a7c-876d-4280-af63-839243c7c595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workforce Management'])[1]/following::a[1]</value>
      <webElementGuid>43e43f40-d048-4cdd-97d4-0026ffd76ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/preceding::a[1]</value>
      <webElementGuid>bc0ce0fe-ff3e-471d-b7b2-6e0e65addaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Home')]</value>
      <webElementGuid>03cc6aa4-e76a-4461-8460-9afcb7bcc766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>db1aab72-65c8-4fd9-a850-0c18651a62b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MenuItem_Button_Home' and @href = '/Home' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>ae89f840-e20a-4466-8dd6-60586c24e236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
