<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>welcomeText</name>
   <tag></tag>
   <elementGuidId>e44af80c-241f-43b0-820e-029adc9e7aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Hello Wade' or . = 'Hello Wade')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-container']/div/hf-home-app/hf-home-index/hf-home-header/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.home-header__info__name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03462a75-f6e3-41f7-a683-7819a392f32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-header__info__name</value>
      <webElementGuid>11fa1aa1-f939-413d-afd2-e17121ab6282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello Wade</value>
      <webElementGuid>cc5a91cf-31d9-46fe-ac5d-2c48d31a145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-container&quot;)/div[@class=&quot;page-wide&quot;]/hf-home-app[1]/hf-home-index[1]/hf-home-header[1]/div[@class=&quot;home-header__wrapper&quot;]/div[@class=&quot;home-header__info&quot;]/div[@class=&quot;home-header__info&quot;]/span[@class=&quot;home-header__info__name&quot;]</value>
      <webElementGuid>2fe3ca64-ed07-4226-add8-7b8d494201bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-container']/div/hf-home-app/hf-home-index/hf-home-header/div/div/div/span</value>
      <webElementGuid>2f67be9a-8b84-44d5-aa3b-f50261a01e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[1]/following::span[1]</value>
      <webElementGuid>2f4f67b4-d507-4bf3-a5ec-cc3e8a3ca432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/preceding::span[2]</value>
      <webElementGuid>736c7587-7649-4ce4-8397-1d489c0b8762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No messages to show'])[1]/preceding::span[2]</value>
      <webElementGuid>cefaf01d-253a-4e00-bdca-ddd875a7745d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello Wade']/parent::*</value>
      <webElementGuid>203b9c97-5da8-4c21-8913-41242e74573f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>b64276e6-260f-4420-8b0d-2eb2a4c12e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hello Wade' or . = 'Hello Wade')]</value>
      <webElementGuid>d7cbfeee-6e16-4b34-af9c-e2e6861b1ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
